# Generated by Django 2.1.7 on 2019-03-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challenge_nb_points_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('MIC', 'MISC'), ('PPC', 'Programming'), ('WEB', 'Web'), ('FOR', 'Forensics'), ('REV', 'Reverse'), ('PWN', 'Pwn'), ('CRY', 'Crypto'), ('NET', 'Network')], default='WEB', max_length=3),
        ),
    ]
