# Generated by Django 2.1.7 on 2019-03-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20190326_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='is_ovh_chall',
        ),
        migrations.AddField(
            model_name='challenge',
            name='company_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
