# Generated by Django 2.1.7 on 2019-03-26 20:58

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_auto_20190326_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctfsettings',
            name='url_challenges_state',
        ),
        migrations.AddField(
            model_name='ctfsettings',
            name='challenges_states_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctfsettings',
            name='challenges_states_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Flag should be in the form ^INSA{.*}$', regex='^INSA{.*}$')]),
        ),
    ]
