# Generated by Django 2.1.7 on 2019-04-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_auto_20190326_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='chall_file',
            new_name='static_url',
        ),
    ]
