# Generated by Django 2.1.7 on 2019-04-28 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0005_teamprofile_ips'),
        ('challenges', '0008_auto_20190410_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTriedChall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_fail', models.TextField(max_length=255)),
                ('chall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
                ('flagger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.TeamProfile')),
            ],
        ),
    ]
