# Generated by Django 2.1.7 on 2019-04-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_teamtriedchall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfsettings',
            name='challenges_states_json',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
