# Generated by Django 2.1.7 on 2019-04-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_auto_20180318_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='ips',
            field=models.TextField(default='{}'),
        ),
    ]
