# Generated by Django 2.1.7 on 2019-04-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0005_teamprofile_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssh',
            name='password',
        ),
        migrations.AddField(
            model_name='ssh',
            name='key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
